name: 🚀 Create Release

on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Create Zip
        run: |
          zip -r BigSur.zip "Big Sur/"
          zip -r Monterey.zip "Monterey/"
     
      - name: Generate Changelog
        run: git log  --format="%C(auto) %h %s" `git tag --sort=-committerdate | head -1`...`git tag --sort=-committerdate | head -2 | tail -1` |cut -d " " -f 2- > changelog.txt     
          
      - name: Upload EFI
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: changelog.txt
          prerelease: ${{ contains(github.ref, 'dev') }}
          files: |
            BigSur.zip
            Monterey.zip
